#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /etc/systemd/system/docker.service
    owner: "root:root"
    permissions: "0644"
    content: |
      [Unit]
      Description=Docker Application Container Engine
      Documentation=http://docs.docker.com
      After=network.target docker.socket wait-for-flanneld.service
      Requires=docker.socket wait-for-flanneld.service

      [Service]
      Type=notify
      EnvironmentFile=-/etc/sysconfig/docker
      EnvironmentFile=-/etc/sysconfig/docker-storage
      
      # This EnvironmentFile is required.
      EnvironmentFile=/run/flannel/subnet.env

      # This works around https://github.com/docker/docker/issues/9468
      Environment=DOCKER_CERT_PATH=/etc/docker

      ExecStart=/usr/bin/docker -d -H fd:// --bip $FLANNEL_SUBNET --mtu $FLANNEL_MTU $OPTIONS $DOCKER_STORAGE_OPTIONS
      Restart=on-failure
      LimitNOFILE=1048576
      LimitNPROC=1048576

      [Install]
      WantedBy=multi-user.target

