#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /usr/local/bin/wait-for-flanneld
    owner: "root:root"
    permissions: "0755"
    content: |
      #!/bin/sh
      
      # This script waits for flannel to provide the /run/flannel/subnet.env
      # file. This can be used to synchronize docker startup with the
      # availability of this file.

      while ! [ -f /run/flannel/subnet.env ]; do
        echo "waiting for flanneld"
        sleep 1
      done

      echo flanneld is active

      exit 0
  - path: /etc/systemd/system/wait-for-flanneld.service
    owner: "root:root"
    permissions: "0644"
    content: |
      [Unit]
      Description=Wait for flanneld to provide subnet/mtu information
      After=network.target flanneld.service
      Requires=flanneld.service

      [Service]
      Type=oneshot
      ExecStart=/usr/local/bin/wait-for-flanneld

      [Install]
      WantedBy=multi-user.target

